set xlabel font "Helvetica,12"
set ylabel font "Helvetica,12"
set tics font "Helvetica,12"
set title font "Helvetica,12"
set xlabel "x"
set ylabel "y(x)"
set title "Soluções da EDO com h = 0.1"
plot "dados_11.3_5a.dat" u 1:2 w p pt 7 ps 2 t"Solução y(x)"
g(x) = exp(-10.0*x)
replot g(x) w l lw 2 t"Solução Teórica"
